[pytest]
addopts = --color=yes -s --log-disable=alembic.runtime.migration
filterwarnings =
    ignore::DeprecationWarning:testcontainers.core.waiting_utils
    ignore::DeprecationWarning:testcontainers.generic
