"""Add patreon fields to user

Revision ID: 27c98ec7944f
Revises: 5eafd4b604e8
Create Date: 2025-12-31 08:07:19.836790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c98ec7944f'
down_revision = '5eafd4b604e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patreon_id', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('patreon_email', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_patreon_id'), ['patreon_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_patreon_id'))
        batch_op.drop_column('patreon_email')
        batch_op.drop_column('patreon_id')

    # ### end Alembic commands ###
