"""Add patreon token fields to User

Revision ID: 5eafd5183cba
Revises: 27c98ec7944f
Create Date: 2026-01-17 07:05:00.318745

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5eafd5183cba'
down_revision = '27c98ec7944f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patreon_access_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('patreon_refresh_token', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('patreon_refresh_token')
        batch_op.drop_column('patreon_access_token')

    # ### end Alembic commands ###
