#!/bin/bash  
# Pre-commit hook to auto-generate __version__.py  

GENERATE_SCRIPT="generate_version.sh"  
VERSION_FILE="forgesteel_warehouse/__version__.py"  

bash "$GENERATE_SCRIPT" "$VERSION_FILE"  

git add "$VERSION_FILE"  

exit 0  